nodes:
  - name: web1
    host: 192.168.100.101
    state: present
  - name: web2
    host: 192.168.100.102
    state: present
  - name: db1
    host: 192.168.101.101
    state: present
  - name: db2
    host: 192.168.101.102
    state: present