vips:
  - name: VS_Web_API
    description: Web API VIP
    port: 443
    destination: 192.168.100.1
    snat: automap
    pool: pool_web
    profiles:
      - name: clientssl
        context: client-side
      - tcp
      - http
      
  - name: VS_DB
    description: Database VIP
    port: 80
    destination: 192.168.100.2
    irules:
      - RULE_HTTPS_REDIRECT
    profiles:
      - http
  
  - name: VS_DB_443
    description: Database VIP
    port: 443
    destination: 192.168.100.2
    pool: pool_db
    profiles:
      - name: clientssl
        context: client-side
      - tcp
      - http