nodes:
  - name: web1
    host: 192.168.100.101
    state: present
  - name: web2
    host: 192.168.100.102
    state: present
  - name: db1
    host: 192.168.101.101
    state: present
  - name: db2
    host: 192.168.101.102
    state: present

pools:
  - name: pool_web
    description: Web server pool
    lb_method: round-robin
    monitors:
      - http
    members: 
      - name: web1
        host: 192.168.100.101
        port: 80
      - name: web2
        host: 192.168.100.102
        port: 80
  - name: pool_db
    description: Database server pool
    lb_method: round-robin
    monitors:
      - http
    members: 
      - name: db1
        host: 192.168.101.101
        port: 80
      - name: db2
        host: 192.168.101.102
        port: 80

vips:
  - name: VS_Web_API
    description: Web API VIP
    port: 443
    destination: 192.168.100.1
    snat: automap
    pool: pool_web
    profiles:
      - name: clientssl
        context: client-side
      - tcp
      - http
  - name: VS_DB
    description: Database VIP
    port: 80
    destination: 192.168.100.2
    snat: automap
    pool: pool_db
    profiles:
      - tcp
      - http